# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 11:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_change'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Change',
        ),
    ]
